config/routes.rb
VotaPrato::Application.routes.draw do
  
  resources :comentarios

  resources :qualificacoes

  resources :clientes

  
  match 'rack',
	:to => proc{|env|[200,{"Content-Type"=>"text/html"}, ["App Rack numa rota Rails"]]}  

  match 'banana' => 'restaurantes#index'
  match 'ufc(/:nome)'=> 'Restaurantes#ufc'
  match ':controller(/:action(/:id(.:format)))'

end

app/models/nome.rb
class Nome < ActiveRecord::Base
end

app/controllers/nomes_controller.rb
class NomesController < ApplicationController
  # GET /nomes
  # GET /nomes.xml
  def index
    @nomes = Nome.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @nomes }
    end
  end

  # GET /nomes/1
  # GET /nomes/1.xml
  def show
    @nome = Nome.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @nome }
    end
  end

  # GET /nomes/new
  # GET /nomes/new.xml
  def new
    @nome = Nome.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @nome }
    end
  end

  # GET /nomes/1/edit
  def edit
    @nome = Nome.find(params[:id])
  end

  # POST /nomes
  # POST /nomes.xml
  def create
    @nome = Nome.new(params[:nome])

    respond_to do |format|
      if @nome.save
        format.html { redirect_to(@nome, :notice => 'Nome was successfully created.') }
        format.xml  { render :xml => @nome, :status => :created, :location => @nome }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @nome.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nomes/1
  # PUT /nomes/1.xml
  def update
    @nome = Nome.find(params[:id])

    respond_to do |format|
      if @nome.update_attributes(params[:nome])
        format.html { redirect_to(@nome, :notice => 'Nome was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @nome.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nomes/1
  # DELETE /nomes/1.xml
  def destroy
    @nome = Nome.find(params[:id])
    @nome.destroy

    respond_to do |format|
      format.html { redirect_to(nomes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/nomes_helper.rb
module NomesHelper
end

app/views/nomes/_form.html.erb
<%= form_for(@nome) do |f| %>
  <% if @nome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nome.errors.count, "error") %> prohibited this nome from being saved:</h2>

      <ul>
      <% @nome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nomes/edit.html.erb
<h1>Editing nome</h1>

<%= render 'form' %>

<%= link_to 'Show', @nome %> |
<%= link_to 'Back', nomes_path %>

app/views/nomes/index.html.erb
<h1>Listing nomes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nomes.each do |nome| %>
  <tr>
    <td><%= nome.nome %></td>
    <td><%= link_to 'Show', nome %></td>
    <td><%= link_to 'Edit', edit_nome_path(nome) %></td>
    <td><%= link_to 'Destroy', nome, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nome', new_nome_path %>

app/views/nomes/new.html.erb
<h1>New nome</h1>

<%= render 'form' %>

<%= link_to 'Back', nomes_path %>

app/views/nomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @nome.nome %>
</p>


<%= link_to 'Edit', edit_nome_path(@nome) %> |
<%= link_to 'Back', nomes_path %>